version: '3'
services:
  worker:
    image: kaybenleroll/rminions:latest
    environment:
      - REDIS=redis
    depends_on:
      - redis

  redis:
    image: redis:7.0.11-alpine3.18
    ports:
      - "6379:6379"
